version: '3'

services:
    pgadmin:
        container_name: pgadmin_m151
        image: dpage/pgadmin4:5.2
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.ch
            - PGADMIN_DEFAULT_PASSWORD=passwort
        ports:
            - 5050:80
        networks:
            - houseConstruct
        volumes:
            - pgadmin-data:/root/.pgadmin
        depends_on:
            - postgres
    
    postgres:
        container_name: postgres_m151
        image: postgres:13-alpine
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=passwort
            - POSTGRES_DB=houseConstruct
        ports:
            - 5432:5432
        networks:
            - houseConstruct
        volumes:
            - postgres-db:/var/libe/postresql/data

networks:
    houseConstruct:
        driver: bridge
volumes:
    pgadmin-data:
    postgres-db:
